// automatically generated by the FlatBuffers compiler, do not modify

import { DelegateCall } from '../executorch-flatbuffer/delegate-call';
import { FreeCall } from '../executorch-flatbuffer/free-call';
import { JumpFalseCall } from '../executorch-flatbuffer/jump-false-call';
import { KernelCall } from '../executorch-flatbuffer/kernel-call';
import { MoveCall } from '../executorch-flatbuffer/move-call';


export enum InstructionArguments {
  NONE = 0,
  KernelCall = 1,
  DelegateCall = 2,
  MoveCall = 3,
  JumpFalseCall = 4,
  FreeCall = 5
}

export function unionToInstructionArguments(
  type: InstructionArguments,
  accessor: (obj:DelegateCall|FreeCall|JumpFalseCall|KernelCall|MoveCall) => DelegateCall|FreeCall|JumpFalseCall|KernelCall|MoveCall|null
): DelegateCall|FreeCall|JumpFalseCall|KernelCall|MoveCall|null {
  switch(InstructionArguments[type]) {
    case 'NONE': return null; 
    case 'KernelCall': return accessor(new KernelCall())! as KernelCall;
    case 'DelegateCall': return accessor(new DelegateCall())! as DelegateCall;
    case 'MoveCall': return accessor(new MoveCall())! as MoveCall;
    case 'JumpFalseCall': return accessor(new JumpFalseCall())! as JumpFalseCall;
    case 'FreeCall': return accessor(new FreeCall())! as FreeCall;
    default: return null;
  }
}

export function unionListToInstructionArguments(
  type: InstructionArguments, 
  accessor: (index: number, obj:DelegateCall|FreeCall|JumpFalseCall|KernelCall|MoveCall) => DelegateCall|FreeCall|JumpFalseCall|KernelCall|MoveCall|null, 
  index: number
): DelegateCall|FreeCall|JumpFalseCall|KernelCall|MoveCall|null {
  switch(InstructionArguments[type]) {
    case 'NONE': return null; 
    case 'KernelCall': return accessor(index, new KernelCall())! as KernelCall;
    case 'DelegateCall': return accessor(index, new DelegateCall())! as DelegateCall;
    case 'MoveCall': return accessor(index, new MoveCall())! as MoveCall;
    case 'JumpFalseCall': return accessor(index, new JumpFalseCall())! as JumpFalseCall;
    case 'FreeCall': return accessor(index, new FreeCall())! as FreeCall;
    default: return null;
  }
}
