// automatically generated by the FlatBuffers compiler, do not modify

import { Bool } from '../executorch-flatbuffer/bool';
import { BoolList } from '../executorch-flatbuffer/bool-list';
import { Double } from '../executorch-flatbuffer/double';
import { DoubleList } from '../executorch-flatbuffer/double-list';
import { Int } from '../executorch-flatbuffer/int';
import { IntList } from '../executorch-flatbuffer/int-list';
import { Null } from '../executorch-flatbuffer/null';
import { OptionalTensorList } from '../executorch-flatbuffer/optional-tensor-list';
import { String } from '../executorch-flatbuffer/string';
import { Tensor } from '../executorch-flatbuffer/tensor';
import { TensorList } from '../executorch-flatbuffer/tensor-list';


export enum KernelTypes {
  NONE = 0,
  Null = 1,
  Int = 2,
  Bool = 3,
  Double = 4,
  Tensor = 5,
  String = 6,
  IntList = 7,
  DoubleList = 8,
  BoolList = 9,
  TensorList = 10,
  OptionalTensorList = 11
}

export function unionToKernelTypes(
  type: KernelTypes,
  accessor: (obj:Bool|BoolList|Double|DoubleList|Int|IntList|Null|OptionalTensorList|String|Tensor|TensorList) => Bool|BoolList|Double|DoubleList|Int|IntList|Null|OptionalTensorList|String|Tensor|TensorList|null
): Bool|BoolList|Double|DoubleList|Int|IntList|Null|OptionalTensorList|String|Tensor|TensorList|null {
  switch(KernelTypes[type]) {
    case 'NONE': return null; 
    case 'Null': return accessor(new Null())! as Null;
    case 'Int': return accessor(new Int())! as Int;
    case 'Bool': return accessor(new Bool())! as Bool;
    case 'Double': return accessor(new Double())! as Double;
    case 'Tensor': return accessor(new Tensor())! as Tensor;
    case 'String': return accessor(new String())! as String;
    case 'IntList': return accessor(new IntList())! as IntList;
    case 'DoubleList': return accessor(new DoubleList())! as DoubleList;
    case 'BoolList': return accessor(new BoolList())! as BoolList;
    case 'TensorList': return accessor(new TensorList())! as TensorList;
    case 'OptionalTensorList': return accessor(new OptionalTensorList())! as OptionalTensorList;
    default: return null;
  }
}

export function unionListToKernelTypes(
  type: KernelTypes, 
  accessor: (index: number, obj:Bool|BoolList|Double|DoubleList|Int|IntList|Null|OptionalTensorList|String|Tensor|TensorList) => Bool|BoolList|Double|DoubleList|Int|IntList|Null|OptionalTensorList|String|Tensor|TensorList|null, 
  index: number
): Bool|BoolList|Double|DoubleList|Int|IntList|Null|OptionalTensorList|String|Tensor|TensorList|null {
  switch(KernelTypes[type]) {
    case 'NONE': return null; 
    case 'Null': return accessor(index, new Null())! as Null;
    case 'Int': return accessor(index, new Int())! as Int;
    case 'Bool': return accessor(index, new Bool())! as Bool;
    case 'Double': return accessor(index, new Double())! as Double;
    case 'Tensor': return accessor(index, new Tensor())! as Tensor;
    case 'String': return accessor(index, new String())! as String;
    case 'IntList': return accessor(index, new IntList())! as IntList;
    case 'DoubleList': return accessor(index, new DoubleList())! as DoubleList;
    case 'BoolList': return accessor(index, new BoolList())! as BoolList;
    case 'TensorList': return accessor(index, new TensorList())! as TensorList;
    case 'OptionalTensorList': return accessor(index, new OptionalTensorList())! as OptionalTensorList;
    default: return null;
  }
}
