// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class MoveCall {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MoveCall {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMoveCall(bb:flatbuffers.ByteBuffer, obj?:MoveCall):MoveCall {
  return (obj || new MoveCall()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMoveCall(bb:flatbuffers.ByteBuffer, obj?:MoveCall):MoveCall {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MoveCall()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

moveFrom():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

moveTo():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startMoveCall(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMoveFrom(builder:flatbuffers.Builder, moveFrom:number) {
  builder.addFieldInt32(0, moveFrom, 0);
}

static addMoveTo(builder:flatbuffers.Builder, moveTo:number) {
  builder.addFieldInt32(1, moveTo, 0);
}

static endMoveCall(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMoveCall(builder:flatbuffers.Builder, moveFrom:number, moveTo:number):flatbuffers.Offset {
  MoveCall.startMoveCall(builder);
  MoveCall.addMoveFrom(builder, moveFrom);
  MoveCall.addMoveTo(builder, moveTo);
  return MoveCall.endMoveCall(builder);
}
}
