// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class NamedData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NamedData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNamedData(bb:flatbuffers.ByteBuffer, obj?:NamedData):NamedData {
  return (obj || new NamedData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNamedData(bb:flatbuffers.ByteBuffer, obj?:NamedData):NamedData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NamedData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

segmentIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startNamedData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addSegmentIndex(builder:flatbuffers.Builder, segmentIndex:number) {
  builder.addFieldInt32(1, segmentIndex, 0);
}

static endNamedData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNamedData(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, segmentIndex:number):flatbuffers.Offset {
  NamedData.startNamedData(builder);
  NamedData.addKey(builder, keyOffset);
  NamedData.addSegmentIndex(builder, segmentIndex);
  return NamedData.endNamedData(builder);
}
}
