// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DeviceType } from '../executorch-flatbuffer/device-type';


export class NonConstBufferDevice {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):NonConstBufferDevice {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNonConstBufferDevice(bb:flatbuffers.ByteBuffer, obj?:NonConstBufferDevice):NonConstBufferDevice {
  return (obj || new NonConstBufferDevice()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNonConstBufferDevice(bb:flatbuffers.ByteBuffer, obj?:NonConstBufferDevice):NonConstBufferDevice {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NonConstBufferDevice()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bufferIdx():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

deviceType():DeviceType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : DeviceType.CPU;
}

deviceIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

static startNonConstBufferDevice(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addBufferIdx(builder:flatbuffers.Builder, bufferIdx:number) {
  builder.addFieldInt32(0, bufferIdx, 0);
}

static addDeviceType(builder:flatbuffers.Builder, deviceType:DeviceType) {
  builder.addFieldInt8(1, deviceType, DeviceType.CPU);
}

static addDeviceIndex(builder:flatbuffers.Builder, deviceIndex:number) {
  builder.addFieldInt8(2, deviceIndex, 0);
}

static endNonConstBufferDevice(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNonConstBufferDevice(builder:flatbuffers.Builder, bufferIdx:number, deviceType:DeviceType, deviceIndex:number):flatbuffers.Offset {
  NonConstBufferDevice.startNonConstBufferDevice(builder);
  NonConstBufferDevice.addBufferIdx(builder, bufferIdx);
  NonConstBufferDevice.addDeviceType(builder, deviceType);
  NonConstBufferDevice.addDeviceIndex(builder, deviceIndex);
  return NonConstBufferDevice.endNonConstBufferDevice(builder);
}
}
