// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SubsegmentOffsets {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SubsegmentOffsets {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSubsegmentOffsets(bb:flatbuffers.ByteBuffer, obj?:SubsegmentOffsets):SubsegmentOffsets {
  return (obj || new SubsegmentOffsets()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSubsegmentOffsets(bb:flatbuffers.ByteBuffer, obj?:SubsegmentOffsets):SubsegmentOffsets {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SubsegmentOffsets()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

segmentIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

offsets(index: number):bigint|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb!.__vector(this.bb_pos + offset) + index * 8) : BigInt(0);
}

offsetsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSubsegmentOffsets(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSegmentIndex(builder:flatbuffers.Builder, segmentIndex:number) {
  builder.addFieldInt32(0, segmentIndex, 0);
}

static addOffsets(builder:flatbuffers.Builder, offsetsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, offsetsOffset, 0);
}

static createOffsetsVector(builder:flatbuffers.Builder, data:bigint[]):flatbuffers.Offset {
  builder.startVector(8, data.length, 8);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt64(data[i]!);
  }
  return builder.endVector();
}

static startOffsetsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 8);
}

static endSubsegmentOffsets(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSubsegmentOffsets(builder:flatbuffers.Builder, segmentIndex:number, offsetsOffset:flatbuffers.Offset):flatbuffers.Offset {
  SubsegmentOffsets.startSubsegmentOffsets(builder);
  SubsegmentOffsets.addSegmentIndex(builder, segmentIndex);
  SubsegmentOffsets.addOffsets(builder, offsetsOffset);
  return SubsegmentOffsets.endSubsegmentOffsets(builder);
}
}
