// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Bool {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Bool {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBool(bb:flatbuffers.ByteBuffer, obj?:Bool):Bool {
  return (obj || new Bool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBool(bb:flatbuffers.ByteBuffer, obj?:Bool):Bool {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Bool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

boolVal():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startBool(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBoolVal(builder:flatbuffers.Builder, boolVal:boolean) {
  builder.addFieldInt8(0, +boolVal, +false);
}

static endBool(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createBool(builder:flatbuffers.Builder, boolVal:boolean):flatbuffers.Offset {
  Bool.startBool(builder);
  Bool.addBoolVal(builder, boolVal);
  return Bool.endBool(builder);
}
}
