// automatically generated by the FlatBuffers compiler, do not modify

import { Bool } from '../vkgraph/bool';
import { BoolList } from '../vkgraph/bool-list';
import { Double } from '../vkgraph/double';
import { DoubleList } from '../vkgraph/double-list';
import { Int } from '../vkgraph/int';
import { IntList } from '../vkgraph/int-list';
import { Null } from '../vkgraph/null';
import { String } from '../vkgraph/string';
import { SymInt } from '../vkgraph/sym-int';
import { ValueList } from '../vkgraph/value-list';
import { VkTensor } from '../vkgraph/vk-tensor';


export enum GraphTypes {
  NONE = 0,
  Null = 1,
  Int = 2,
  Double = 3,
  Bool = 4,
  VkTensor = 5,
  IntList = 6,
  DoubleList = 7,
  BoolList = 8,
  ValueList = 9,
  String = 10,
  SymInt = 11
}

export function unionToGraphTypes(
  type: GraphTypes,
  accessor: (obj:Bool|BoolList|Double|DoubleList|Int|IntList|Null|String|SymInt|ValueList|VkTensor) => Bool|BoolList|Double|DoubleList|Int|IntList|Null|String|SymInt|ValueList|VkTensor|null
): Bool|BoolList|Double|DoubleList|Int|IntList|Null|String|SymInt|ValueList|VkTensor|null {
  switch(GraphTypes[type]) {
    case 'NONE': return null; 
    case 'Null': return accessor(new Null())! as Null;
    case 'Int': return accessor(new Int())! as Int;
    case 'Double': return accessor(new Double())! as Double;
    case 'Bool': return accessor(new Bool())! as Bool;
    case 'VkTensor': return accessor(new VkTensor())! as VkTensor;
    case 'IntList': return accessor(new IntList())! as IntList;
    case 'DoubleList': return accessor(new DoubleList())! as DoubleList;
    case 'BoolList': return accessor(new BoolList())! as BoolList;
    case 'ValueList': return accessor(new ValueList())! as ValueList;
    case 'String': return accessor(new String())! as String;
    case 'SymInt': return accessor(new SymInt())! as SymInt;
    default: return null;
  }
}

export function unionListToGraphTypes(
  type: GraphTypes, 
  accessor: (index: number, obj:Bool|BoolList|Double|DoubleList|Int|IntList|Null|String|SymInt|ValueList|VkTensor) => Bool|BoolList|Double|DoubleList|Int|IntList|Null|String|SymInt|ValueList|VkTensor|null, 
  index: number
): Bool|BoolList|Double|DoubleList|Int|IntList|Null|String|SymInt|ValueList|VkTensor|null {
  switch(GraphTypes[type]) {
    case 'NONE': return null; 
    case 'Null': return accessor(index, new Null())! as Null;
    case 'Int': return accessor(index, new Int())! as Int;
    case 'Double': return accessor(index, new Double())! as Double;
    case 'Bool': return accessor(index, new Bool())! as Bool;
    case 'VkTensor': return accessor(index, new VkTensor())! as VkTensor;
    case 'IntList': return accessor(index, new IntList())! as IntList;
    case 'DoubleList': return accessor(index, new DoubleList())! as DoubleList;
    case 'BoolList': return accessor(index, new BoolList())! as BoolList;
    case 'ValueList': return accessor(index, new ValueList())! as ValueList;
    case 'String': return accessor(index, new String())! as String;
    case 'SymInt': return accessor(index, new SymInt())! as SymInt;
    default: return null;
  }
}
