// automatically generated by the FlatBuffers compiler, do not modify

export enum VkDataType {
  BOOL = 0,
  UINT8 = 1,
  INT8 = 2,
  INT32 = 3,
  FLOAT16 = 4,
  FLOAT32 = 5,
  FLOAT64 = 6,
  INT64 = 7,
  UNSET = 127
}
