// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { OperatorCall } from '../vkgraph/operator-call';
import { VkBytes } from '../vkgraph/vk-bytes';
import { VkMemoryLayout } from '../vkgraph/vk-memory-layout';
import { VkStorageType } from '../vkgraph/vk-storage-type';
import { VkValue } from '../vkgraph/vk-value';


export class VkGraph {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VkGraph {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVkGraph(bb:flatbuffers.ByteBuffer, obj?:VkGraph):VkGraph {
  return (obj || new VkGraph()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVkGraph(bb:flatbuffers.ByteBuffer, obj?:VkGraph):VkGraph {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VkGraph()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('VK00');
}

version():string|null
version(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
version(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

chain(index: number, obj?:OperatorCall):OperatorCall|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new OperatorCall()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

chainLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

values(index: number, obj?:VkValue):VkValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VkValue()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

valuesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

inputIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

inputIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

inputIdsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

outputIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

outputIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

outputIdsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

constants(index: number, obj?:VkBytes):VkBytes|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new VkBytes()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

constantsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

shaders(index: number, obj?:VkBytes):VkBytes|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new VkBytes()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

shadersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

storageTypeOverride():VkStorageType {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VkStorageType.DEFAULT_STORAGE;
}

memoryLayoutOverride():VkMemoryLayout {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VkMemoryLayout.DEFAULT_LAYOUT;
}

static startVkGraph(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addVersion(builder:flatbuffers.Builder, versionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, versionOffset, 0);
}

static addChain(builder:flatbuffers.Builder, chainOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, chainOffset, 0);
}

static createChainVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startChainVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addValues(builder:flatbuffers.Builder, valuesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, valuesOffset, 0);
}

static createValuesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startValuesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addInputIds(builder:flatbuffers.Builder, inputIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, inputIdsOffset, 0);
}

static createInputIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createInputIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createInputIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startInputIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addOutputIds(builder:flatbuffers.Builder, outputIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, outputIdsOffset, 0);
}

static createOutputIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createOutputIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createOutputIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startOutputIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addConstants(builder:flatbuffers.Builder, constantsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, constantsOffset, 0);
}

static createConstantsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startConstantsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addShaders(builder:flatbuffers.Builder, shadersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, shadersOffset, 0);
}

static createShadersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startShadersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStorageTypeOverride(builder:flatbuffers.Builder, storageTypeOverride:VkStorageType) {
  builder.addFieldInt8(7, storageTypeOverride, VkStorageType.DEFAULT_STORAGE);
}

static addMemoryLayoutOverride(builder:flatbuffers.Builder, memoryLayoutOverride:VkMemoryLayout) {
  builder.addFieldInt8(8, memoryLayoutOverride, VkMemoryLayout.DEFAULT_LAYOUT);
}

static endVkGraph(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishVkGraphBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'VK00');
}

static finishSizePrefixedVkGraphBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'VK00', true);
}

static createVkGraph(builder:flatbuffers.Builder, versionOffset:flatbuffers.Offset, chainOffset:flatbuffers.Offset, valuesOffset:flatbuffers.Offset, inputIdsOffset:flatbuffers.Offset, outputIdsOffset:flatbuffers.Offset, constantsOffset:flatbuffers.Offset, shadersOffset:flatbuffers.Offset, storageTypeOverride:VkStorageType, memoryLayoutOverride:VkMemoryLayout):flatbuffers.Offset {
  VkGraph.startVkGraph(builder);
  VkGraph.addVersion(builder, versionOffset);
  VkGraph.addChain(builder, chainOffset);
  VkGraph.addValues(builder, valuesOffset);
  VkGraph.addInputIds(builder, inputIdsOffset);
  VkGraph.addOutputIds(builder, outputIdsOffset);
  VkGraph.addConstants(builder, constantsOffset);
  VkGraph.addShaders(builder, shadersOffset);
  VkGraph.addStorageTypeOverride(builder, storageTypeOverride);
  VkGraph.addMemoryLayoutOverride(builder, memoryLayoutOverride);
  return VkGraph.endVkGraph(builder);
}
}
