// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { VkDataType } from '../vkgraph/vk-data-type';
import { VkMemoryLayout } from '../vkgraph/vk-memory-layout';
import { VkStorageType } from '../vkgraph/vk-storage-type';


export class VkTensor {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VkTensor {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVkTensor(bb:flatbuffers.ByteBuffer, obj?:VkTensor):VkTensor {
  return (obj || new VkTensor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVkTensor(bb:flatbuffers.ByteBuffer, obj?:VkTensor):VkTensor {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VkTensor()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

datatype():VkDataType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : VkDataType.BOOL;
}

dims(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

dimsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dimsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

constantId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

memObjId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

storageType():VkStorageType {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VkStorageType.DEFAULT_STORAGE;
}

memoryLayout():VkMemoryLayout {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VkMemoryLayout.DEFAULT_LAYOUT;
}

stagingDatatype():VkDataType {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : VkDataType.UNSET;
}

static startVkTensor(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addDatatype(builder:flatbuffers.Builder, datatype:VkDataType) {
  builder.addFieldInt8(0, datatype, VkDataType.BOOL);
}

static addDims(builder:flatbuffers.Builder, dimsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, dimsOffset, 0);
}

static createDimsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createDimsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createDimsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startDimsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addConstantId(builder:flatbuffers.Builder, constantId:number) {
  builder.addFieldInt32(2, constantId, 0);
}

static addMemObjId(builder:flatbuffers.Builder, memObjId:number) {
  builder.addFieldInt32(3, memObjId, 0);
}

static addStorageType(builder:flatbuffers.Builder, storageType:VkStorageType) {
  builder.addFieldInt8(4, storageType, VkStorageType.DEFAULT_STORAGE);
}

static addMemoryLayout(builder:flatbuffers.Builder, memoryLayout:VkMemoryLayout) {
  builder.addFieldInt8(5, memoryLayout, VkMemoryLayout.DEFAULT_LAYOUT);
}

static addStagingDatatype(builder:flatbuffers.Builder, stagingDatatype:VkDataType) {
  builder.addFieldInt8(6, stagingDatatype, VkDataType.UNSET);
}

static endVkTensor(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVkTensor(builder:flatbuffers.Builder, datatype:VkDataType, dimsOffset:flatbuffers.Offset, constantId:number, memObjId:number, storageType:VkStorageType, memoryLayout:VkMemoryLayout, stagingDatatype:VkDataType):flatbuffers.Offset {
  VkTensor.startVkTensor(builder);
  VkTensor.addDatatype(builder, datatype);
  VkTensor.addDims(builder, dimsOffset);
  VkTensor.addConstantId(builder, constantId);
  VkTensor.addMemObjId(builder, memObjId);
  VkTensor.addStorageType(builder, storageType);
  VkTensor.addMemoryLayout(builder, memoryLayout);
  VkTensor.addStagingDatatype(builder, stagingDatatype);
  return VkTensor.endVkTensor(builder);
}
}
